---
setups:
  CF-NetCDF:
    fields:
    - Coordinate variables: [time, latitude, longitude, depth, altitude, air_pressure, sea_water_pressure]
      Coordinate bounds: [time_bounds, latitude_bounds, longitude_bounds, depth_bounds, altitude_bounds, air_pressure_bounds, sea_water_pressure_bounds]
  Learnings from Nansen Legacy logging system:
    activity:
      fields:
      - Required: [eventDate, eventTime, stationName, decimalLatitude, decimalLongitude, gearType, pi_details, recordedBy_details]
        Recommended: [id, statID, catalogNumber, endDate, endTime, endDecimalLatitude, endDecimalLongitude, minimumDepthInMeters, maximumDepthInMeters, minimumElevationInMeters, maximumElevationInMeters,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,comments1]
    default:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion, comments1]
    Fish:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,scientificName,comments1]
    Ice core:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details, seaIceCoreType]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,seaIceCoreLengthInCentimeters,seaIceThicknessInCentimeters,seaIceFreeboardInCentimeters,comments1]
    Macrofauna:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,scientificName,comments1]
    Macrozooplankton:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,scientificName,comments1]
    Megafauna:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,scientificName,comments1]
    Meiofauna:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,scientificName,comments1]
    Melt pond water:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details, sampleVolumeInMilliliters]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,filteredVolumeInMilliliters,filter,comments1]
    Melt pond:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,seaIceMeltpondTemperatureInCelsius,seaIceMeltpondSalinity,comments1]
    Meroplankton:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,scientificName,comments1]
    Mesozooplankton:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,scientificName,comments1]
    Microzooplankton:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,scientificName,comments1]
    Niskin:
      fields:
      - Required: [parentID, gearType, sampleType, bottleNumber, minimumDepthInMeters, maximumDepthInMeters, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,dataFilename, comments1]
    Protist:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,scientificName,comments1]
    Sea water:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details, sampleVolumeInMilliliters]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,filteredVolumeInMilliliters,filter,comments1]
    Small meiofauna:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,scientificName,comments1]
    Small mesozooplankton:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,scientificName,comments1]
    Under ice water:
      fields:
      - Required: [parentID, sampleType, pi_details, recordedBy_details, sampleVolumeInMilliliters]
        Recommended: [id, catalogNumber,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,filteredVolumeInMilliliters,filter,comments1]
  Darwin Core:
    Sampling Event:
      Event Core:
        fields:
        - Required: [eventID,eventDate,samplingProtocol]
          Recommended: [sampleSizeValue, sampleSizeUnit, parentEventID, samplingEffort, locationID, decimalLatitude, decimalLongitude, geodeticDatum, footprintWKT, footprintSRS, countryCode, occurrenceStatus]
          Suggestions: 'from source'
        Source: 'https://rs.gbif.org/core/dwc_event_2022-02-02.xml'
        Required CSV: True
      Occurrence Extension:
        fields:
        - Required: [occurrenceID,eventID,basisOfRecord,scientificName]
          Recommended: [taxonRank,kingdom,individualCount,organismQuantity,organismQuantityType]
          Suggestions: 'from source'
        Source: 'https://rs.gbif.org/core/dwc_occurrence_2022-02-02.xml'
        Required CSV: True
      Extended Measurement or Facts Extension:
        fields:
        - Required: [measurementID,occurrenceID,eventID,measurementType,measurementValue,measurementUnit]
          Recommended: 'from source'
        Source: 'https://rs.gbif.org/extension/obis/extended_measurement_or_fact.xml'
        Required CSV: False
      Material Sample Extension:
        fields:
        - Required: [materialSampleID,eventID,materialSampleType]
          Recommended: 'from source'
        Source: 'https://rs.gbif.org/extension/ggbn/materialsample.xml'
        Required CSV: False
      Resource Relationship Extension:
        fields:
        - Required: [resourceRelationshipID,resourceID,relatedResourceID, eventID]
          Recommended: 'from source'
        Source: 'https://rs.gbif.org/extension/dwc/resource_relationship_2022-02-02.xml'
        Required CSV: False
      Simple Multimedia Extension:
        fields:
        - Required: [type,format,identifier,eventID,occurrenceID]
          Recommended: 'from source'
        Source: 'https://rs.gbif.org/extension/gbif/1.0/multimedia.xml'
        Required CSV: False
...
