setups:
  - name: activity
    fields:
      required: [eventDate, eventTime, stationName, decimalLatitude, decimalLongitude, gearType, pis, recordedBys]
      recommended: [id, catalogNumber, endDate, endTime, endDecimalLatitude, endDecimalLongitude, minimumDepthInMeters, maximumDepthInMeters, minimumElevationInMeters, maximumElevationInMeters,samplingProtocolDoc,samplingProtocolSection,samplingProtocolVersion,comments1]
